name: macOS Build

on:
  push:
    branches: [ master ]  # Using master since that's what I see in your branch name
  pull_request:
    branches: [ master ]

jobs:
  macOS-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          brew update
          brew install imlib2 libx11 libxft libexif
        
      - name: Build
        run: |
          make clean
          make -s OPT_DEP_DEFAULT=1 HAVE_INOTIFY=0 \
            CPPFLAGS="-I/opt/homebrew/include -I/opt/homebrew/include/freetype2" \
            LDLIBS="-L/opt/homebrew/lib"
          
      - name: Package Binary
        run: |
          # Create a directory for the release
          mkdir -p release
          # Copy the binary and make it executable
          cp nsxiv release/
          chmod +x release/nsxiv
          # Add documentation
          cp README.md LICENSE release/
          
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: nsxiv-macos
          path: release/
          retention-days: 90
